operator:
  functional: inversediffusion.operator.downsample.DownsampleOperator
  args: null
  kwargs:
    in_shape: !!python/tuple [1, 3, 256, 256]
    scale_factor: 4

distance:
  functional: inversediffusion.distance.rmse.DistanceRMSE
  args: null
  kwargs: null